### PR TITLE
Add autofield to apps

### PR DESCRIPTION
**Pull request by kike-reveni**
Fixes https://github.com/agateblue/django-dynamic-preferences/issues/276

### CODE REVIEW

**Review by agateblue — APPROVED** [review]
That's perfect, thank you!

**Comment by sbruno** [comment]
@agateblue Is it planned to include this fix in a future release anytime soon? Thanks!

**Comment by agateblue** [comment]
How did I forget to merge that? Thank you @sbruno for the reminder, I'll push a release on PyPi next week :)

**Comment by agateblue** [comment]
@sbruno @kike-reveni the 1.13.0 release that include this change is now live on PyPi :)

https://pypi.org/project/django-dynamic-preferences/1.13.0/

**Pull request merged**
